run:
  # timeout for analysis
  deadline: 4m

linters-settings:
  govet:
    # Don't report about shadowed variables
    check-shadowing: false
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

linters:
  enable-all: true
  disable:
    # Init functions are used by loggers throughout the codebase.
    - gochecknoinits

    # Global variables are used by loggers.
    - gochecknoglobals

    # Some lines are over 80 characters on purpose and we don't want to make
    # them even longer by marking them as 'nolint'.
    - lll

    # We don't care (enough) about misaligned structs to lint that.
    - maligned

    # We have long functions, especially in tests. Moving or renaming those
    # would trigger funlen problems that we may not want to solve at that time.
    - funlen

issues:
  exclude-rules:
    # Fix false positives because of build flags.
    - path: itest/.*
      linters:
        - unused
        - deadcode
        - varcheck
