language: go
cache:
  directories:
    - $GOCACHE

go:
  - "1.13.x"

# Remove Travis' default flag --depth=50 from the git clone command to make sure
# we have the whole git history, including the commit we lint against.
git:
  depth: false

# Allow fetching of private repos by using SSH instead of HTTPS for go mod.
before_install:
  - git config --global url."git@github.com:lightninglabs".insteadOf "https://github.com/lightninglabs"
  - git config --global url."git@github.com:guggero".insteadOf "https://github.com/guggero"
  - git config --global url."git@github.com:roasbeef".insteadOf "https://github.com/roasbeef"

env:
  global:
    - GOCACHE=$HOME/.go-build
    - GO111MODULE=on

sudo: required

jobs:
  include:
    - stage: Build
      script:
        - make unit pkg=... case=_NONE_
        - make lint workers=1
        - make btcd
    - stage: Test
      script: make unit-race
      name: Unit Race
    - script: make itest
      name: Btcd Integration

after_script:
  - echo "Uploading to termbin.com..." && find *.log | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
  - echo "Uploading to file.io..." && tar -zcvO *.log | curl -s -F 'file=@-;filename=logs.tar.gz' https://file.io | xargs -r0 printf 'logs.tar.gz uploaded to %s\n'
