{
 "title": "Account State",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total Number of Accounts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(account_count) by (acct_state)",
     "legendFormat": "{{acct_state}}"
    }
   ]
  },
  {
   "title": "Total Account Balances",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "sum(account_balance) by (acct_state)",
     "legendFormat": "{{acct_state}}"
    }
   ]
  },
  {
   "title": "Account Transactions Per Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Transactions" }
   ],
   "targets": [
    {
     "expr": "count(account_tx_fee_paid_block) by (block_height)",
     "legendFormat": "{{block_height}}"
    }
   ]
  },
  {
   "title": "Total Fees Paid by Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(account_tx_fee_paid_block) by (block_height)",
     "legendFormat": "{{block_height}}"
    }
   ]
  },
  {
   "title": "Account size distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of accounts" }
   ],
   "targets": [
    { "expr": "account_balance", "legendFormat": "Account size" }
   ]
  },
  {
   "title": "LSAT statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count by (lsat) (account_count{lsat!=\"<none>\", lsat!=\"\"}))",
     "legendFormat": "Number of users"
    },
    {
     "expr": "avg(avg by (lsat) (account_count{lsat!=\"<none>\", lsat!=\"\"}))",
     "legendFormat": "Average accounts per user"
    }
   ]
  },
  {
   "title": "Top 10 tokens by number of accounts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "topk(10, count by (lsat) (account_count{lsat!=\"\", lsat!=\"<none>\"}))",
     "legendFormat": "{{lsat}}"
    }
   ]
  }
 ]
}