{
 "title": "Batches",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Open Order Interest",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(order_units_unfulfilled{order_type=\"Ask\"}) * 100000",
     "legendFormat": "ask_open_interest_sat"
    },
    {
     "expr": "sum(order_units_unfulfilled{order_type=\"Bid\"}) * 100000",
     "legendFormat": "bid_open_interest_sat"
    }
   ]
  },
  {
   "title": "WIP Depth Chart",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (order_type, order_rate) (order_units_unfulfilled)",
     "legendFormat": "{{order_type}} : {{order_rate}}"
    }
   ]
  },
  {
   "title": "Number of Orders Matched",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "batch_num_matched_orders", "legendFormat": "Matched orders {{batch_id}}" }
   ]
  },
  {
   "title": "Number of Units Matched (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(batch_units_matched)", "legendFormat": "Matched units (avg)" }
   ]
  },
  {
   "title": "Number of Accounts involved",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "batch_num_accounts", "legendFormat": "Accounts involved {{batch_id}}" }
   ]
  },
  {
   "title": "Clearing Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "batch_clearing_price", "legendFormat": "Clearing price {{batch_id}}" }
   ]
  },
  {
   "title": "Auction Fees",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "currencyBTC", "label": "Satoshis" }
   ],
   "targets": [
    { "expr": "batch_auction_fees", "legendFormat": "Auction fees {{batch_id}}" }
   ]
  },
  {
   "title": "TX Inputs/Outputs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "batch_tx_num_inputs", "legendFormat": "TX inputs {{batch_id}}" },
    { "expr": "batch_tx_num_outputs", "legendFormat": "TX outputs {{batch_id}}" }
   ]
  },
  {
   "title": "TX Fees paid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "currencyBTC", "label": "Satoshis" }
   ],
   "targets": [
    { "expr": "batch_tx_fees", "legendFormat": "TX fees {{batch_id}}" }
   ]
  },
  {
   "title": "Total number of batches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Number of batches" }
   ],
   "targets": [
    { "expr": "batch_count" }
   ]
  }
 ]
}