{
 "title": "Pool gRPC Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Inbound Request Rates [2m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{app=\"subasta\"}[2m]) !=0) by (grpc_method)\n",
     "legendFormat": "{{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Inbound Error Rates [2m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{app=\"subasta\", grpc_code!=\"OK\"}[2m])) by (grpc_method)\n",
     "legendFormat": "{{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Response Error Rate % [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{app=\"subasta\",grpc_code!=\"OK\"}[2m])) by (grpc_method)\n / \nsum(rate(grpc_server_started_total{app=\"subasta\"}[2m])) by (grpc_method)\n * 100.0\n",
     "legendFormat": "{{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Auction Messages Sent [2m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grpc_server_msg_sent_total{app=\"subasta\", grpc_method=\"SubscribeBatchAuction\"}[2m])",
     "legendFormat": "Msgs Sent"
    }
   ]
  },
  {
   "title": "Batch Snapshot Queries [2m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{app=\"subasta\", grpc_method=\"BatchSnapshot\", grpc_code=\"OK\"}[2m])",
     "legendFormat": "ok_resp"
    },
    {
     "expr": "rate(grpc_server_handled_total{app=\"subasta\", grpc_method=\"BatchSnapshot\", grpc_code!=\"OK\"}[2m])",
     "legendFormat": "err_resp"
    }
   ]
  },
  {
   "title": "Account Management Errors [5m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{app=\"subasta\", grpc_method=\"ModifyAccount\",grpc_code!=\"OK\"}[5m])",
     "legendFormat": "modify_account"
    },
    {
     "expr": "rate(grpc_server_handled_total{app=\"subasta\", grpc_method=\"InitAccount\", grpc_code!=\"OK\"}[5m])",
     "legendFormat": "init_account"
    },
    {
     "expr": "rate(grpc_server_handled_total{app=\"subasta\", grpc_method=\"ReserveAccount\", grpc_code!=\"OK\"}[5m])",
     "legendFormat": "reserve_account"
    }
   ]
  },
  {
   "title": "New Trader Connections/Disconnects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(grpc_server_handled_total{app=\"subasta\", grpc_method=\"SubscribeBatchAuction\", grpc_code!=\"OK\"}[5m])",
     "legendFormat": "failed_conns_per_second"
    },
    {
     "expr": "increase(grpc_server_handled_total{app=\"subasta\", grpc_method=\"SubscribeBatchAuction\", grpc_code=\"OK\"}[5m])",
     "legendFormat": "new_conns_per_second"
    }
   ]
  }
 ]
}