{
 "title": "Order State",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Order Spread",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(order_rate{order_type=\"Ask\"})",
     "legendFormat": "lowest_ask"
    },
    {
     "expr": "max(order_rate{order_type=\"Bid\"})",
     "legendFormat": "highest_bid"
    }
   ]
  },
  {
   "title": "All: Total Number by Order State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(order_count) by (order_state, order_type)",
     "legendFormat": "{{order_type}}: {{order_state}}"
    }
   ]
  },
  {
   "title": "All: Total Order Units by Order State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(order_units) by (order_state, order_type)",
     "legendFormat": "{{order_type}}: {{order_state}}"
    }
   ]
  },
  {
   "title": "All: Order Unit distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of orders" }
   ],
   "targets": [
    { "expr": "order_units", "legendFormat": "Order units" }
   ]
  },
  {
   "title": "All: Order Duration distribution (in days/144 blocks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Number of orders" }
   ],
   "targets": [
    { "expr": "order_duration/144", "legendFormat": "Order duration (days)" }
   ]
  },
  {
   "title": "All: Order Rate distribution (% per 30 days)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Number of orders" }
   ],
   "targets": [
    { "expr": "order_rate/1e9*(30*144)*100", "legendFormat": "Order rate" }
   ]
  },
  {
   "title": "Ask: Total Number by Order State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(order_count{order_type=\"Ask\"}) by (order_state)",
     "legendFormat": "{{order_state}}"
    }
   ]
  },
  {
   "title": "Ask: Total Order Units by Order State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(order_units{order_type=\"Ask\"}) by (order_state)",
     "legendFormat": "{{order_state}}"
    }
   ]
  },
  {
   "title": "Ask: Order Unit distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Number of orders" }
   ],
   "targets": [
    {
     "expr": "order_units{order_type=\"Ask\"}",
     "legendFormat": "Order units"
    }
   ]
  },
  {
   "title": "Ask: Order Duration distribution (in days/144 blocks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Number of orders" }
   ],
   "targets": [
    {
     "expr": "order_duration{order_type=\"Ask\"}/144",
     "legendFormat": "Order duration (days)"
    }
   ]
  },
  {
   "title": "Ask: Order Rate distribution (% per 30 days)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Number of orders" }
   ],
   "targets": [
    {
     "expr": "order_rate{order_type=\"Ask\"}/1e9*(30*144)*100",
     "legendFormat": "Order rate"
    }
   ]
  },
  {
   "title": "Bid: Total Number by Order State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(order_count{order_type=\"Bid\"}) by (order_state)",
     "legendFormat": "{{order_state}}"
    }
   ]
  },
  {
   "title": "Bid: Total Order Units by Order State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(order_units{order_type=\"Bid\"}) by (order_state)",
     "legendFormat": "{{order_state}}"
    }
   ]
  },
  {
   "title": "Bid: Order Unit distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "Number of orders" }
   ],
   "targets": [
    {
     "expr": "order_units{order_type=\"Bid\"}",
     "legendFormat": "Order units"
    }
   ]
  },
  {
   "title": "Bid: Order Duration distribution (in days/144 blocks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "Number of orders" }
   ],
   "targets": [
    {
     "expr": "order_duration{order_type=\"Bid\"}/144",
     "legendFormat": "Order duration (days)"
    }
   ]
  },
  {
   "title": "Bid: Order Rate distribution (% per 30 days)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "Number of orders" }
   ],
   "targets": [
    {
     "expr": "order_rate{order_type=\"Bid\"}/1e9*(30*144)*100",
     "legendFormat": "Order rate"
    }
   ]
  }
 ]
}