{
 "title": "Pool Pulse",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Auction Fees",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "batch_total_revenue", "legendFormat": "total_sats" }
   ]
  },
  {
   "title": "Total Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "batch_total_volume", "legendFormat": "total_sats" }
   ]
  },
  {
   "title": "Batch Execution Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "batch_execution_latency_ms_bucket"
    }
   ]
  },
  {
   "title": "Batch Match Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "batch_match_latency_ms_bucket" }
   ]
  },
  {
   "title": "Failures Per Batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(batch_failures) by (reason, batch_id)"
    }
   ]
  },
  {
   "title": "Match Attempts Per Batch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(batch_match_attempt) by (batch_id)"
    }
   ]
  },
  {
   "title": "Execution Attempts Per Batch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(batch_exe_attempt) by (batch_id)"
    }
   ]
  }
 ]
}