// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package clmrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvalidOrder_FailReason int32

const (
	InvalidOrder_INVALID_AMT InvalidOrder_FailReason = 0
)

var InvalidOrder_FailReason_name = map[int32]string{
	0: "INVALID_AMT",
}

var InvalidOrder_FailReason_value = map[string]int32{
	"INVALID_AMT": 0,
}

func (x InvalidOrder_FailReason) String() string {
	return proto.EnumName(InvalidOrder_FailReason_name, int32(x))
}

func (InvalidOrder_FailReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{15, 0}
}

type ServerInitAccountRequest struct {
	//*
	//Transaction output of the account. Has to be unspent and be a P2WSH of
	//the account script below. The amount must also exactly correspond to the
	//account value below.
	AccountPoint *OutPoint `protobuf:"bytes,1,opt,name=account_point,json=accountPoint,proto3" json:"account_point,omitempty"`
	//*
	//The script used to create the account point.
	AccountScript []byte `protobuf:"bytes,2,opt,name=account_script,json=accountScript,proto3" json:"account_script,omitempty"`
	//*
	//The value of the account in satoshis. Must match the amount of the
	//account_point output.
	AccountValue int64 `protobuf:"varint,3,opt,name=account_value,json=accountValue,proto3" json:"account_value,omitempty"`
	//*
	//Validity of the account in seconds.
	AccountDuration int64 `protobuf:"varint,4,opt,name=account_duration,json=accountDuration,proto3" json:"account_duration,omitempty"`
	//*
	//The user's sub account key.
	AccountSubKey        []byte   `protobuf:"bytes,5,opt,name=account_sub_key,json=accountSubKey,proto3" json:"account_sub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInitAccountRequest) Reset()         { *m = ServerInitAccountRequest{} }
func (m *ServerInitAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ServerInitAccountRequest) ProtoMessage()    {}
func (*ServerInitAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *ServerInitAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInitAccountRequest.Unmarshal(m, b)
}
func (m *ServerInitAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInitAccountRequest.Marshal(b, m, deterministic)
}
func (m *ServerInitAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInitAccountRequest.Merge(m, src)
}
func (m *ServerInitAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ServerInitAccountRequest.Size(m)
}
func (m *ServerInitAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInitAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInitAccountRequest proto.InternalMessageInfo

func (m *ServerInitAccountRequest) GetAccountPoint() *OutPoint {
	if m != nil {
		return m.AccountPoint
	}
	return nil
}

func (m *ServerInitAccountRequest) GetAccountScript() []byte {
	if m != nil {
		return m.AccountScript
	}
	return nil
}

func (m *ServerInitAccountRequest) GetAccountValue() int64 {
	if m != nil {
		return m.AccountValue
	}
	return 0
}

func (m *ServerInitAccountRequest) GetAccountDuration() int64 {
	if m != nil {
		return m.AccountDuration
	}
	return 0
}

func (m *ServerInitAccountRequest) GetAccountSubKey() []byte {
	if m != nil {
		return m.AccountSubKey
	}
	return nil
}

type ServerInitAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInitAccountResponse) Reset()         { *m = ServerInitAccountResponse{} }
func (m *ServerInitAccountResponse) String() string { return proto.CompactTextString(m) }
func (*ServerInitAccountResponse) ProtoMessage()    {}
func (*ServerInitAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *ServerInitAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInitAccountResponse.Unmarshal(m, b)
}
func (m *ServerInitAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInitAccountResponse.Marshal(b, m, deterministic)
}
func (m *ServerInitAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInitAccountResponse.Merge(m, src)
}
func (m *ServerInitAccountResponse) XXX_Size() int {
	return xxx_messageInfo_ServerInitAccountResponse.Size(m)
}
func (m *ServerInitAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInitAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInitAccountResponse proto.InternalMessageInfo

type ServerCloseAccountRequest struct {
	//*
	//The user's sub account key.
	AccountSubKey []byte `protobuf:"bytes,1,opt,name=account_sub_key,json=accountSubKey,proto3" json:"account_sub_key,omitempty"`
	//*
	//Specifies where the money from the account should be sent to.
	CloseOutputs         map[int64][]byte `protobuf:"bytes,2,rep,name=close_outputs,json=closeOutputs,proto3" json:"close_outputs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServerCloseAccountRequest) Reset()         { *m = ServerCloseAccountRequest{} }
func (m *ServerCloseAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ServerCloseAccountRequest) ProtoMessage()    {}
func (*ServerCloseAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *ServerCloseAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCloseAccountRequest.Unmarshal(m, b)
}
func (m *ServerCloseAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCloseAccountRequest.Marshal(b, m, deterministic)
}
func (m *ServerCloseAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCloseAccountRequest.Merge(m, src)
}
func (m *ServerCloseAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ServerCloseAccountRequest.Size(m)
}
func (m *ServerCloseAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCloseAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCloseAccountRequest proto.InternalMessageInfo

func (m *ServerCloseAccountRequest) GetAccountSubKey() []byte {
	if m != nil {
		return m.AccountSubKey
	}
	return nil
}

func (m *ServerCloseAccountRequest) GetCloseOutputs() map[int64][]byte {
	if m != nil {
		return m.CloseOutputs
	}
	return nil
}

type ServerCloseAccountResponse struct {
	//*
	//Signature that allows the user to broadcast their account closing
	//transaction.
	CloseSig             []byte   `protobuf:"bytes,1,opt,name=close_sig,json=closeSig,proto3" json:"close_sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerCloseAccountResponse) Reset()         { *m = ServerCloseAccountResponse{} }
func (m *ServerCloseAccountResponse) String() string { return proto.CompactTextString(m) }
func (*ServerCloseAccountResponse) ProtoMessage()    {}
func (*ServerCloseAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *ServerCloseAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCloseAccountResponse.Unmarshal(m, b)
}
func (m *ServerCloseAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCloseAccountResponse.Marshal(b, m, deterministic)
}
func (m *ServerCloseAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCloseAccountResponse.Merge(m, src)
}
func (m *ServerCloseAccountResponse) XXX_Size() int {
	return xxx_messageInfo_ServerCloseAccountResponse.Size(m)
}
func (m *ServerCloseAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCloseAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCloseAccountResponse proto.InternalMessageInfo

func (m *ServerCloseAccountResponse) GetCloseSig() []byte {
	if m != nil {
		return m.CloseSig
	}
	return nil
}

type ServerOrderRequest struct {
	// Types that are valid to be assigned to Details:
	//	*ServerOrderRequest_Ask
	//	*ServerOrderRequest_Bid
	Details              isServerOrderRequest_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ServerOrderRequest) Reset()         { *m = ServerOrderRequest{} }
func (m *ServerOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ServerOrderRequest) ProtoMessage()    {}
func (*ServerOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *ServerOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerOrderRequest.Unmarshal(m, b)
}
func (m *ServerOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerOrderRequest.Marshal(b, m, deterministic)
}
func (m *ServerOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerOrderRequest.Merge(m, src)
}
func (m *ServerOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ServerOrderRequest.Size(m)
}
func (m *ServerOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerOrderRequest proto.InternalMessageInfo

type isServerOrderRequest_Details interface {
	isServerOrderRequest_Details()
}

type ServerOrderRequest_Ask struct {
	Ask *Ask `protobuf:"bytes,1,opt,name=ask,proto3,oneof"`
}

type ServerOrderRequest_Bid struct {
	Bid *Bid `protobuf:"bytes,2,opt,name=bid,proto3,oneof"`
}

func (*ServerOrderRequest_Ask) isServerOrderRequest_Details() {}

func (*ServerOrderRequest_Bid) isServerOrderRequest_Details() {}

func (m *ServerOrderRequest) GetDetails() isServerOrderRequest_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *ServerOrderRequest) GetAsk() *Ask {
	if x, ok := m.GetDetails().(*ServerOrderRequest_Ask); ok {
		return x.Ask
	}
	return nil
}

func (m *ServerOrderRequest) GetBid() *Bid {
	if x, ok := m.GetDetails().(*ServerOrderRequest_Bid); ok {
		return x.Bid
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerOrderRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerOrderRequest_Ask)(nil),
		(*ServerOrderRequest_Bid)(nil),
	}
}

type ServerOrderResponse struct {
	// Types that are valid to be assigned to Details:
	//	*ServerOrderResponse_InvalidOrder
	//	*ServerOrderResponse_Accepted
	Details              isServerOrderResponse_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ServerOrderResponse) Reset()         { *m = ServerOrderResponse{} }
func (m *ServerOrderResponse) String() string { return proto.CompactTextString(m) }
func (*ServerOrderResponse) ProtoMessage()    {}
func (*ServerOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *ServerOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerOrderResponse.Unmarshal(m, b)
}
func (m *ServerOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerOrderResponse.Marshal(b, m, deterministic)
}
func (m *ServerOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerOrderResponse.Merge(m, src)
}
func (m *ServerOrderResponse) XXX_Size() int {
	return xxx_messageInfo_ServerOrderResponse.Size(m)
}
func (m *ServerOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerOrderResponse proto.InternalMessageInfo

type isServerOrderResponse_Details interface {
	isServerOrderResponse_Details()
}

type ServerOrderResponse_InvalidOrder struct {
	InvalidOrder *InvalidOrder `protobuf:"bytes,1,opt,name=invalid_order,json=invalidOrder,proto3,oneof"`
}

type ServerOrderResponse_Accepted struct {
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3,oneof"`
}

func (*ServerOrderResponse_InvalidOrder) isServerOrderResponse_Details() {}

func (*ServerOrderResponse_Accepted) isServerOrderResponse_Details() {}

func (m *ServerOrderResponse) GetDetails() isServerOrderResponse_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *ServerOrderResponse) GetInvalidOrder() *InvalidOrder {
	if x, ok := m.GetDetails().(*ServerOrderResponse_InvalidOrder); ok {
		return x.InvalidOrder
	}
	return nil
}

func (m *ServerOrderResponse) GetAccepted() bool {
	if x, ok := m.GetDetails().(*ServerOrderResponse_Accepted); ok {
		return x.Accepted
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerOrderResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerOrderResponse_InvalidOrder)(nil),
		(*ServerOrderResponse_Accepted)(nil),
	}
}

type ClientAuctionMessage struct {
	// Types that are valid to be assigned to Msg:
	//	*ClientAuctionMessage_Prepare
	//	*ClientAuctionMessage_Accept
	//	*ClientAuctionMessage_Sign
	//	*ClientAuctionMessage_Finalize
	Msg                  isClientAuctionMessage_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClientAuctionMessage) Reset()         { *m = ClientAuctionMessage{} }
func (m *ClientAuctionMessage) String() string { return proto.CompactTextString(m) }
func (*ClientAuctionMessage) ProtoMessage()    {}
func (*ClientAuctionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *ClientAuctionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientAuctionMessage.Unmarshal(m, b)
}
func (m *ClientAuctionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientAuctionMessage.Marshal(b, m, deterministic)
}
func (m *ClientAuctionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientAuctionMessage.Merge(m, src)
}
func (m *ClientAuctionMessage) XXX_Size() int {
	return xxx_messageInfo_ClientAuctionMessage.Size(m)
}
func (m *ClientAuctionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientAuctionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientAuctionMessage proto.InternalMessageInfo

type isClientAuctionMessage_Msg interface {
	isClientAuctionMessage_Msg()
}

type ClientAuctionMessage_Prepare struct {
	Prepare *OrderMatchPrepare `protobuf:"bytes,1,opt,name=prepare,proto3,oneof"`
}

type ClientAuctionMessage_Accept struct {
	Accept *OrderMatchAccept `protobuf:"bytes,2,opt,name=accept,proto3,oneof"`
}

type ClientAuctionMessage_Sign struct {
	Sign *OrderMatchSign `protobuf:"bytes,3,opt,name=sign,proto3,oneof"`
}

type ClientAuctionMessage_Finalize struct {
	Finalize *OrderMatchFinalize `protobuf:"bytes,4,opt,name=finalize,proto3,oneof"`
}

func (*ClientAuctionMessage_Prepare) isClientAuctionMessage_Msg() {}

func (*ClientAuctionMessage_Accept) isClientAuctionMessage_Msg() {}

func (*ClientAuctionMessage_Sign) isClientAuctionMessage_Msg() {}

func (*ClientAuctionMessage_Finalize) isClientAuctionMessage_Msg() {}

func (m *ClientAuctionMessage) GetMsg() isClientAuctionMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ClientAuctionMessage) GetPrepare() *OrderMatchPrepare {
	if x, ok := m.GetMsg().(*ClientAuctionMessage_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *ClientAuctionMessage) GetAccept() *OrderMatchAccept {
	if x, ok := m.GetMsg().(*ClientAuctionMessage_Accept); ok {
		return x.Accept
	}
	return nil
}

func (m *ClientAuctionMessage) GetSign() *OrderMatchSign {
	if x, ok := m.GetMsg().(*ClientAuctionMessage_Sign); ok {
		return x.Sign
	}
	return nil
}

func (m *ClientAuctionMessage) GetFinalize() *OrderMatchFinalize {
	if x, ok := m.GetMsg().(*ClientAuctionMessage_Finalize); ok {
		return x.Finalize
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientAuctionMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientAuctionMessage_Prepare)(nil),
		(*ClientAuctionMessage_Accept)(nil),
		(*ClientAuctionMessage_Sign)(nil),
		(*ClientAuctionMessage_Finalize)(nil),
	}
}

type OrderMatchPrepare struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderMatchPrepare) Reset()         { *m = OrderMatchPrepare{} }
func (m *OrderMatchPrepare) String() string { return proto.CompactTextString(m) }
func (*OrderMatchPrepare) ProtoMessage()    {}
func (*OrderMatchPrepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *OrderMatchPrepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMatchPrepare.Unmarshal(m, b)
}
func (m *OrderMatchPrepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMatchPrepare.Marshal(b, m, deterministic)
}
func (m *OrderMatchPrepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMatchPrepare.Merge(m, src)
}
func (m *OrderMatchPrepare) XXX_Size() int {
	return xxx_messageInfo_OrderMatchPrepare.Size(m)
}
func (m *OrderMatchPrepare) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMatchPrepare.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMatchPrepare proto.InternalMessageInfo

type OrderMatchAccept struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderMatchAccept) Reset()         { *m = OrderMatchAccept{} }
func (m *OrderMatchAccept) String() string { return proto.CompactTextString(m) }
func (*OrderMatchAccept) ProtoMessage()    {}
func (*OrderMatchAccept) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *OrderMatchAccept) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMatchAccept.Unmarshal(m, b)
}
func (m *OrderMatchAccept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMatchAccept.Marshal(b, m, deterministic)
}
func (m *OrderMatchAccept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMatchAccept.Merge(m, src)
}
func (m *OrderMatchAccept) XXX_Size() int {
	return xxx_messageInfo_OrderMatchAccept.Size(m)
}
func (m *OrderMatchAccept) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMatchAccept.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMatchAccept proto.InternalMessageInfo

type OrderMatchSign struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderMatchSign) Reset()         { *m = OrderMatchSign{} }
func (m *OrderMatchSign) String() string { return proto.CompactTextString(m) }
func (*OrderMatchSign) ProtoMessage()    {}
func (*OrderMatchSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{9}
}

func (m *OrderMatchSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMatchSign.Unmarshal(m, b)
}
func (m *OrderMatchSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMatchSign.Marshal(b, m, deterministic)
}
func (m *OrderMatchSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMatchSign.Merge(m, src)
}
func (m *OrderMatchSign) XXX_Size() int {
	return xxx_messageInfo_OrderMatchSign.Size(m)
}
func (m *OrderMatchSign) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMatchSign.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMatchSign proto.InternalMessageInfo

type OrderMatchFinalize struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderMatchFinalize) Reset()         { *m = OrderMatchFinalize{} }
func (m *OrderMatchFinalize) String() string { return proto.CompactTextString(m) }
func (*OrderMatchFinalize) ProtoMessage()    {}
func (*OrderMatchFinalize) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{10}
}

func (m *OrderMatchFinalize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMatchFinalize.Unmarshal(m, b)
}
func (m *OrderMatchFinalize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMatchFinalize.Marshal(b, m, deterministic)
}
func (m *OrderMatchFinalize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMatchFinalize.Merge(m, src)
}
func (m *OrderMatchFinalize) XXX_Size() int {
	return xxx_messageInfo_OrderMatchFinalize.Size(m)
}
func (m *OrderMatchFinalize) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMatchFinalize.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMatchFinalize proto.InternalMessageInfo

type ServerAuctionMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerAuctionMessage) Reset()         { *m = ServerAuctionMessage{} }
func (m *ServerAuctionMessage) String() string { return proto.CompactTextString(m) }
func (*ServerAuctionMessage) ProtoMessage()    {}
func (*ServerAuctionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{11}
}

func (m *ServerAuctionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerAuctionMessage.Unmarshal(m, b)
}
func (m *ServerAuctionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerAuctionMessage.Marshal(b, m, deterministic)
}
func (m *ServerAuctionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerAuctionMessage.Merge(m, src)
}
func (m *ServerAuctionMessage) XXX_Size() int {
	return xxx_messageInfo_ServerAuctionMessage.Size(m)
}
func (m *ServerAuctionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerAuctionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerAuctionMessage proto.InternalMessageInfo

type Bid struct {
	//*
	//Fixed order rate in parts per million.
	RateFixed int64 `protobuf:"varint,1,opt,name=rate_fixed,json=rateFixed,proto3" json:"rate_fixed,omitempty"`
	//*
	//Order amount in satoshis.
	Amt int64 `protobuf:"varint,2,opt,name=amt,proto3" json:"amt,omitempty"`
	//*
	//Required minimum channel duration in blocks.
	MinDurationBlocks int64 `protobuf:"varint,3,opt,name=min_duration_blocks,json=minDurationBlocks,proto3" json:"min_duration_blocks,omitempty"`
	//*
	//Order nonce, acts as unique order identifier.
	OrderNonce []byte `protobuf:"bytes,7,opt,name=order_nonce,json=orderNonce,proto3" json:"order_nonce,omitempty"`
	//*
	//Signature for the order.
	OrderSig             []byte       `protobuf:"bytes,8,opt,name=order_sig,json=orderSig,proto3" json:"order_sig,omitempty"`
	MultiSigKey          []byte       `protobuf:"bytes,9,opt,name=multi_sig_key,json=multiSigKey,proto3" json:"multi_sig_key,omitempty"`
	NodePub              []byte       `protobuf:"bytes,10,opt,name=node_pub,json=nodePub,proto3" json:"node_pub,omitempty"`
	NodeAddr             *NodeAddress `protobuf:"bytes,11,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	ChanType             uint32       `protobuf:"varint,13,opt,name=chan_type,json=chanType,proto3" json:"chan_type,omitempty"`
	FundingFeeRate       int64        `protobuf:"varint,14,opt,name=funding_fee_rate,json=fundingFeeRate,proto3" json:"funding_fee_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Bid) Reset()         { *m = Bid{} }
func (m *Bid) String() string { return proto.CompactTextString(m) }
func (*Bid) ProtoMessage()    {}
func (*Bid) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{12}
}

func (m *Bid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bid.Unmarshal(m, b)
}
func (m *Bid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bid.Marshal(b, m, deterministic)
}
func (m *Bid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bid.Merge(m, src)
}
func (m *Bid) XXX_Size() int {
	return xxx_messageInfo_Bid.Size(m)
}
func (m *Bid) XXX_DiscardUnknown() {
	xxx_messageInfo_Bid.DiscardUnknown(m)
}

var xxx_messageInfo_Bid proto.InternalMessageInfo

func (m *Bid) GetRateFixed() int64 {
	if m != nil {
		return m.RateFixed
	}
	return 0
}

func (m *Bid) GetAmt() int64 {
	if m != nil {
		return m.Amt
	}
	return 0
}

func (m *Bid) GetMinDurationBlocks() int64 {
	if m != nil {
		return m.MinDurationBlocks
	}
	return 0
}

func (m *Bid) GetOrderNonce() []byte {
	if m != nil {
		return m.OrderNonce
	}
	return nil
}

func (m *Bid) GetOrderSig() []byte {
	if m != nil {
		return m.OrderSig
	}
	return nil
}

func (m *Bid) GetMultiSigKey() []byte {
	if m != nil {
		return m.MultiSigKey
	}
	return nil
}

func (m *Bid) GetNodePub() []byte {
	if m != nil {
		return m.NodePub
	}
	return nil
}

func (m *Bid) GetNodeAddr() *NodeAddress {
	if m != nil {
		return m.NodeAddr
	}
	return nil
}

func (m *Bid) GetChanType() uint32 {
	if m != nil {
		return m.ChanType
	}
	return 0
}

func (m *Bid) GetFundingFeeRate() int64 {
	if m != nil {
		return m.FundingFeeRate
	}
	return 0
}

type Ask struct {
	//*
	//Fixed order rate in parts per million.
	RateFixed int64 `protobuf:"varint,1,opt,name=rate_fixed,json=rateFixed,proto3" json:"rate_fixed,omitempty"`
	//*
	//Order amount in satoshis.
	Amt int64 `protobuf:"varint,2,opt,name=amt,proto3" json:"amt,omitempty"`
	//*
	//Required minimum channel duration in blocks.
	MaxDurationBlocks int64 `protobuf:"varint,3,opt,name=max_duration_blocks,json=maxDurationBlocks,proto3" json:"max_duration_blocks,omitempty"`
	//*
	//Order nonce, acts as unique order identifier.
	OrderNonce []byte `protobuf:"bytes,7,opt,name=order_nonce,json=orderNonce,proto3" json:"order_nonce,omitempty"`
	//*
	//Signature for the order.
	OrderSig             []byte       `protobuf:"bytes,8,opt,name=order_sig,json=orderSig,proto3" json:"order_sig,omitempty"`
	MultiSigKey          []byte       `protobuf:"bytes,9,opt,name=multi_sig_key,json=multiSigKey,proto3" json:"multi_sig_key,omitempty"`
	NodePub              []byte       `protobuf:"bytes,10,opt,name=node_pub,json=nodePub,proto3" json:"node_pub,omitempty"`
	NodeAddr             *NodeAddress `protobuf:"bytes,11,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	ChanType             uint32       `protobuf:"varint,13,opt,name=chan_type,json=chanType,proto3" json:"chan_type,omitempty"`
	FundingFeeRate       int64        `protobuf:"varint,14,opt,name=funding_fee_rate,json=fundingFeeRate,proto3" json:"funding_fee_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Ask) Reset()         { *m = Ask{} }
func (m *Ask) String() string { return proto.CompactTextString(m) }
func (*Ask) ProtoMessage()    {}
func (*Ask) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{13}
}

func (m *Ask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ask.Unmarshal(m, b)
}
func (m *Ask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ask.Marshal(b, m, deterministic)
}
func (m *Ask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ask.Merge(m, src)
}
func (m *Ask) XXX_Size() int {
	return xxx_messageInfo_Ask.Size(m)
}
func (m *Ask) XXX_DiscardUnknown() {
	xxx_messageInfo_Ask.DiscardUnknown(m)
}

var xxx_messageInfo_Ask proto.InternalMessageInfo

func (m *Ask) GetRateFixed() int64 {
	if m != nil {
		return m.RateFixed
	}
	return 0
}

func (m *Ask) GetAmt() int64 {
	if m != nil {
		return m.Amt
	}
	return 0
}

func (m *Ask) GetMaxDurationBlocks() int64 {
	if m != nil {
		return m.MaxDurationBlocks
	}
	return 0
}

func (m *Ask) GetOrderNonce() []byte {
	if m != nil {
		return m.OrderNonce
	}
	return nil
}

func (m *Ask) GetOrderSig() []byte {
	if m != nil {
		return m.OrderSig
	}
	return nil
}

func (m *Ask) GetMultiSigKey() []byte {
	if m != nil {
		return m.MultiSigKey
	}
	return nil
}

func (m *Ask) GetNodePub() []byte {
	if m != nil {
		return m.NodePub
	}
	return nil
}

func (m *Ask) GetNodeAddr() *NodeAddress {
	if m != nil {
		return m.NodeAddr
	}
	return nil
}

func (m *Ask) GetChanType() uint32 {
	if m != nil {
		return m.ChanType
	}
	return 0
}

func (m *Ask) GetFundingFeeRate() int64 {
	if m != nil {
		return m.FundingFeeRate
	}
	return 0
}

type CancelOrder struct {
	OrderNonce           []byte   `protobuf:"bytes,1,opt,name=order_nonce,json=orderNonce,proto3" json:"order_nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrder) Reset()         { *m = CancelOrder{} }
func (m *CancelOrder) String() string { return proto.CompactTextString(m) }
func (*CancelOrder) ProtoMessage()    {}
func (*CancelOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{14}
}

func (m *CancelOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrder.Unmarshal(m, b)
}
func (m *CancelOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrder.Marshal(b, m, deterministic)
}
func (m *CancelOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrder.Merge(m, src)
}
func (m *CancelOrder) XXX_Size() int {
	return xxx_messageInfo_CancelOrder.Size(m)
}
func (m *CancelOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrder.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrder proto.InternalMessageInfo

func (m *CancelOrder) GetOrderNonce() []byte {
	if m != nil {
		return m.OrderNonce
	}
	return nil
}

type InvalidOrder struct {
	OrderNonce           []byte                  `protobuf:"bytes,1,opt,name=order_nonce,json=orderNonce,proto3" json:"order_nonce,omitempty"`
	FailReason           InvalidOrder_FailReason `protobuf:"varint,2,opt,name=fail_reason,json=failReason,proto3,enum=clmrpc.InvalidOrder_FailReason" json:"fail_reason,omitempty"`
	FailString           string                  `protobuf:"bytes,3,opt,name=fail_string,json=failString,proto3" json:"fail_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *InvalidOrder) Reset()         { *m = InvalidOrder{} }
func (m *InvalidOrder) String() string { return proto.CompactTextString(m) }
func (*InvalidOrder) ProtoMessage()    {}
func (*InvalidOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{15}
}

func (m *InvalidOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidOrder.Unmarshal(m, b)
}
func (m *InvalidOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidOrder.Marshal(b, m, deterministic)
}
func (m *InvalidOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidOrder.Merge(m, src)
}
func (m *InvalidOrder) XXX_Size() int {
	return xxx_messageInfo_InvalidOrder.Size(m)
}
func (m *InvalidOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidOrder.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidOrder proto.InternalMessageInfo

func (m *InvalidOrder) GetOrderNonce() []byte {
	if m != nil {
		return m.OrderNonce
	}
	return nil
}

func (m *InvalidOrder) GetFailReason() InvalidOrder_FailReason {
	if m != nil {
		return m.FailReason
	}
	return InvalidOrder_INVALID_AMT
}

func (m *InvalidOrder) GetFailString() string {
	if m != nil {
		return m.FailString
	}
	return ""
}

type Input struct {
	Outpoint             *OutPoint `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	InputValue           int64     `protobuf:"varint,2,opt,name=input_value,json=inputValue,proto3" json:"input_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{16}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetOutpoint() *OutPoint {
	if m != nil {
		return m.Outpoint
	}
	return nil
}

func (m *Input) GetInputValue() int64 {
	if m != nil {
		return m.InputValue
	}
	return 0
}

type ServerModifyAccountRequest struct {
	AccountPoint         *OutPoint                 `protobuf:"bytes,1,opt,name=account_point,json=accountPoint,proto3" json:"account_point,omitempty"`
	NewInputs            *Input                    `protobuf:"bytes,2,opt,name=new_inputs,json=newInputs,proto3" json:"new_inputs,omitempty"`
	Outputs              map[int64][]byte          `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NewAccountBalance    int64                     `protobuf:"varint,4,opt,name=new_account_balance,json=newAccountBalance,proto3" json:"new_account_balance,omitempty"`
	NewAccount           *ServerInitAccountRequest `protobuf:"bytes,5,opt,name=new_account,json=newAccount,proto3" json:"new_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ServerModifyAccountRequest) Reset()         { *m = ServerModifyAccountRequest{} }
func (m *ServerModifyAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ServerModifyAccountRequest) ProtoMessage()    {}
func (*ServerModifyAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{17}
}

func (m *ServerModifyAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerModifyAccountRequest.Unmarshal(m, b)
}
func (m *ServerModifyAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerModifyAccountRequest.Marshal(b, m, deterministic)
}
func (m *ServerModifyAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerModifyAccountRequest.Merge(m, src)
}
func (m *ServerModifyAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ServerModifyAccountRequest.Size(m)
}
func (m *ServerModifyAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerModifyAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerModifyAccountRequest proto.InternalMessageInfo

func (m *ServerModifyAccountRequest) GetAccountPoint() *OutPoint {
	if m != nil {
		return m.AccountPoint
	}
	return nil
}

func (m *ServerModifyAccountRequest) GetNewInputs() *Input {
	if m != nil {
		return m.NewInputs
	}
	return nil
}

func (m *ServerModifyAccountRequest) GetOutputs() map[int64][]byte {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *ServerModifyAccountRequest) GetNewAccountBalance() int64 {
	if m != nil {
		return m.NewAccountBalance
	}
	return 0
}

func (m *ServerModifyAccountRequest) GetNewAccount() *ServerInitAccountRequest {
	if m != nil {
		return m.NewAccount
	}
	return nil
}

type ServerModifyAccountResponse struct {
	NewAccountSig        []byte    `protobuf:"bytes,1,opt,name=new_account_sig,json=newAccountSig,proto3" json:"new_account_sig,omitempty"`
	NewAccountPoint      *OutPoint `protobuf:"bytes,2,opt,name=new_account_point,json=newAccountPoint,proto3" json:"new_account_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServerModifyAccountResponse) Reset()         { *m = ServerModifyAccountResponse{} }
func (m *ServerModifyAccountResponse) String() string { return proto.CompactTextString(m) }
func (*ServerModifyAccountResponse) ProtoMessage()    {}
func (*ServerModifyAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{18}
}

func (m *ServerModifyAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerModifyAccountResponse.Unmarshal(m, b)
}
func (m *ServerModifyAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerModifyAccountResponse.Marshal(b, m, deterministic)
}
func (m *ServerModifyAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerModifyAccountResponse.Merge(m, src)
}
func (m *ServerModifyAccountResponse) XXX_Size() int {
	return xxx_messageInfo_ServerModifyAccountResponse.Size(m)
}
func (m *ServerModifyAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerModifyAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerModifyAccountResponse proto.InternalMessageInfo

func (m *ServerModifyAccountResponse) GetNewAccountSig() []byte {
	if m != nil {
		return m.NewAccountSig
	}
	return nil
}

func (m *ServerModifyAccountResponse) GetNewAccountPoint() *OutPoint {
	if m != nil {
		return m.NewAccountPoint
	}
	return nil
}

type NodeAddress struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeAddress) Reset()         { *m = NodeAddress{} }
func (m *NodeAddress) String() string { return proto.CompactTextString(m) }
func (*NodeAddress) ProtoMessage()    {}
func (*NodeAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{19}
}

func (m *NodeAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAddress.Unmarshal(m, b)
}
func (m *NodeAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAddress.Marshal(b, m, deterministic)
}
func (m *NodeAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAddress.Merge(m, src)
}
func (m *NodeAddress) XXX_Size() int {
	return xxx_messageInfo_NodeAddress.Size(m)
}
func (m *NodeAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAddress proto.InternalMessageInfo

func (m *NodeAddress) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *NodeAddress) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type OutPoint struct {
	//*
	//Raw bytes representing the transaction id.
	TxidBytes []byte `protobuf:"bytes,1,opt,name=txid_bytes,proto3" json:"txid_bytes,omitempty"`
	//*
	//Reversed, hex-encoded string representing the transaction id.
	TxidStr string `protobuf:"bytes,2,opt,name=txid_str,proto3" json:"txid_str,omitempty"`
	//*
	//The index of the output on the transaction.
	OutputIndex          uint32   `protobuf:"varint,3,opt,name=output_index,proto3" json:"output_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutPoint) Reset()         { *m = OutPoint{} }
func (m *OutPoint) String() string { return proto.CompactTextString(m) }
func (*OutPoint) ProtoMessage()    {}
func (*OutPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{20}
}

func (m *OutPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutPoint.Unmarshal(m, b)
}
func (m *OutPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutPoint.Marshal(b, m, deterministic)
}
func (m *OutPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutPoint.Merge(m, src)
}
func (m *OutPoint) XXX_Size() int {
	return xxx_messageInfo_OutPoint.Size(m)
}
func (m *OutPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_OutPoint.DiscardUnknown(m)
}

var xxx_messageInfo_OutPoint proto.InternalMessageInfo

func (m *OutPoint) GetTxidBytes() []byte {
	if m != nil {
		return m.TxidBytes
	}
	return nil
}

func (m *OutPoint) GetTxidStr() string {
	if m != nil {
		return m.TxidStr
	}
	return ""
}

func (m *OutPoint) GetOutputIndex() uint32 {
	if m != nil {
		return m.OutputIndex
	}
	return 0
}

func init() {
	proto.RegisterEnum("clmrpc.InvalidOrder_FailReason", InvalidOrder_FailReason_name, InvalidOrder_FailReason_value)
	proto.RegisterType((*ServerInitAccountRequest)(nil), "clmrpc.ServerInitAccountRequest")
	proto.RegisterType((*ServerInitAccountResponse)(nil), "clmrpc.ServerInitAccountResponse")
	proto.RegisterType((*ServerCloseAccountRequest)(nil), "clmrpc.ServerCloseAccountRequest")
	proto.RegisterMapType((map[int64][]byte)(nil), "clmrpc.ServerCloseAccountRequest.CloseOutputsEntry")
	proto.RegisterType((*ServerCloseAccountResponse)(nil), "clmrpc.ServerCloseAccountResponse")
	proto.RegisterType((*ServerOrderRequest)(nil), "clmrpc.ServerOrderRequest")
	proto.RegisterType((*ServerOrderResponse)(nil), "clmrpc.ServerOrderResponse")
	proto.RegisterType((*ClientAuctionMessage)(nil), "clmrpc.ClientAuctionMessage")
	proto.RegisterType((*OrderMatchPrepare)(nil), "clmrpc.OrderMatchPrepare")
	proto.RegisterType((*OrderMatchAccept)(nil), "clmrpc.OrderMatchAccept")
	proto.RegisterType((*OrderMatchSign)(nil), "clmrpc.OrderMatchSign")
	proto.RegisterType((*OrderMatchFinalize)(nil), "clmrpc.OrderMatchFinalize")
	proto.RegisterType((*ServerAuctionMessage)(nil), "clmrpc.ServerAuctionMessage")
	proto.RegisterType((*Bid)(nil), "clmrpc.Bid")
	proto.RegisterType((*Ask)(nil), "clmrpc.Ask")
	proto.RegisterType((*CancelOrder)(nil), "clmrpc.CancelOrder")
	proto.RegisterType((*InvalidOrder)(nil), "clmrpc.InvalidOrder")
	proto.RegisterType((*Input)(nil), "clmrpc.Input")
	proto.RegisterType((*ServerModifyAccountRequest)(nil), "clmrpc.ServerModifyAccountRequest")
	proto.RegisterMapType((map[int64][]byte)(nil), "clmrpc.ServerModifyAccountRequest.OutputsEntry")
	proto.RegisterType((*ServerModifyAccountResponse)(nil), "clmrpc.ServerModifyAccountResponse")
	proto.RegisterType((*NodeAddress)(nil), "clmrpc.NodeAddress")
	proto.RegisterType((*OutPoint)(nil), "clmrpc.OutPoint")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 1289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x5d, 0x6f, 0xdb, 0x36,
	0x17, 0xb6, 0x6c, 0x27, 0x96, 0x8f, 0xec, 0xc4, 0x61, 0xf2, 0xf6, 0x55, 0x9d, 0x74, 0x4d, 0x55,
	0xac, 0xf0, 0x80, 0xc2, 0x2d, 0x5c, 0x14, 0xe8, 0xda, 0x01, 0x9b, 0x9d, 0x2e, 0x48, 0xb2, 0xa5,
	0x2d, 0xe4, 0xae, 0xeb, 0x9d, 0x40, 0x4b, 0xb4, 0xcb, 0x45, 0xa6, 0x34, 0x91, 0x6a, 0xe2, 0xed,
	0x72, 0x17, 0xfb, 0x3d, 0xfb, 0x43, 0xfb, 0x0d, 0xbd, 0xd8, 0xdd, 0x6e, 0x06, 0x92, 0x92, 0x3f,
	0x62, 0x37, 0x01, 0x8a, 0x5d, 0xee, 0x4e, 0x7c, 0xce, 0x73, 0xce, 0x21, 0xcf, 0x07, 0x79, 0x04,
	0x35, 0x4e, 0x92, 0xf7, 0x24, 0x69, 0xc7, 0x49, 0x24, 0x22, 0xb4, 0xee, 0x87, 0xe3, 0x24, 0xf6,
	0x9b, 0x7b, 0xa3, 0x28, 0x1a, 0x85, 0xe4, 0x01, 0x8e, 0xe9, 0x03, 0xcc, 0x58, 0x24, 0xb0, 0xa0,
	0x11, 0xe3, 0x9a, 0xe5, 0x7c, 0x30, 0xc0, 0xee, 0x2b, 0xb5, 0x63, 0x46, 0x45, 0xd7, 0xf7, 0xa3,
	0x94, 0x09, 0x97, 0xfc, 0x9c, 0x12, 0x2e, 0xd0, 0x63, 0xa8, 0x63, 0x8d, 0x78, 0x71, 0x44, 0x99,
	0xb0, 0x8d, 0x7d, 0xa3, 0x65, 0x75, 0x1a, 0x6d, 0x6d, 0xba, 0xfd, 0x32, 0x15, 0xaf, 0x24, 0xee,
	0xd6, 0x32, 0x9a, 0x5a, 0xa1, 0xcf, 0x61, 0x23, 0x57, 0xe3, 0x7e, 0x42, 0x63, 0x61, 0x17, 0xf7,
	0x8d, 0x56, 0xcd, 0xcd, 0x8d, 0xf5, 0x15, 0x88, 0xee, 0xce, 0xac, 0xbf, 0xc7, 0x61, 0x4a, 0xec,
	0xd2, 0xbe, 0xd1, 0x2a, 0x4d, 0x6d, 0xbd, 0x91, 0x18, 0xfa, 0x02, 0x1a, 0x39, 0x29, 0x48, 0x13,
	0xb5, 0x75, 0xbb, 0xac, 0x78, 0x9b, 0x19, 0xfe, 0x3c, 0x83, 0xd1, 0x3d, 0xd8, 0x9c, 0xba, 0x4d,
	0x07, 0xde, 0x19, 0x99, 0xd8, 0x6b, 0x8b, 0x7e, 0xd3, 0xc1, 0x77, 0x64, 0xe2, 0xec, 0xc2, 0xcd,
	0x15, 0x27, 0xe6, 0x71, 0xc4, 0x38, 0x71, 0xfe, 0x34, 0x72, 0xe9, 0x41, 0x18, 0x71, 0x72, 0x29,
	0x20, 0x2b, 0x5c, 0x18, 0x2b, 0x5c, 0xa0, 0xb7, 0x50, 0xf7, 0xa5, 0xba, 0x17, 0xa5, 0x22, 0x4e,
	0x05, 0xb7, 0x8b, 0xfb, 0xa5, 0x96, 0xd5, 0x79, 0x94, 0x07, 0xee, 0xa3, 0x1e, 0xda, 0x0a, 0x7b,
	0xa9, 0xb5, 0xbe, 0x65, 0x22, 0x99, 0xb8, 0x35, 0x7f, 0x0e, 0x6a, 0x7e, 0x0d, 0x5b, 0x4b, 0x14,
	0xd4, 0x80, 0x52, 0xbe, 0x95, 0x92, 0x2b, 0x3f, 0xd1, 0x0e, 0xac, 0xe9, 0x98, 0xea, 0xc8, 0xeb,
	0xc5, 0xd3, 0xe2, 0x13, 0xc3, 0xf9, 0x12, 0x9a, 0xab, 0xbc, 0xeb, 0xe3, 0xa3, 0x5d, 0xa8, 0xea,
	0x8d, 0x73, 0x3a, 0xca, 0x8e, 0x66, 0x2a, 0xa0, 0x4f, 0x47, 0x0e, 0x06, 0xa4, 0x55, 0x5f, 0x26,
	0x01, 0x49, 0xf2, 0x98, 0xdc, 0x86, 0x12, 0xe6, 0x67, 0x59, 0x69, 0x58, 0xf9, 0x09, 0xbb, 0xfc,
	0xec, 0xa8, 0xe0, 0x4a, 0x89, 0x24, 0x0c, 0x68, 0xa0, 0x76, 0x32, 0x47, 0xe8, 0xd1, 0x40, 0x12,
	0x06, 0x34, 0xe8, 0x55, 0xa1, 0x12, 0x10, 0x81, 0x69, 0xc8, 0x9d, 0x5f, 0x61, 0x7b, 0xc1, 0x45,
	0xb6, 0xad, 0x67, 0x50, 0xa7, 0xec, 0x3d, 0x0e, 0x69, 0xe0, 0x45, 0x52, 0x90, 0x79, 0xdb, 0xc9,
	0x8d, 0x1d, 0x6b, 0xa1, 0x52, 0x3a, 0x2a, 0xb8, 0x35, 0x3a, 0xb7, 0x46, 0x7b, 0x60, 0x62, 0xdf,
	0x27, 0xb1, 0x20, 0x7a, 0x13, 0xe6, 0x51, 0xc1, 0x9d, 0x22, 0xf3, 0xce, 0x3f, 0x18, 0xb0, 0x73,
	0x10, 0x52, 0xc2, 0x44, 0x37, 0xf5, 0x65, 0x49, 0x9d, 0x12, 0xce, 0xf1, 0x88, 0xa0, 0xc7, 0x50,
	0x89, 0x13, 0x12, 0xe3, 0x84, 0x64, 0x8e, 0x6f, 0x4e, 0x3b, 0x40, 0x7a, 0x38, 0xc5, 0xc2, 0x7f,
	0xf7, 0x4a, 0x13, 0x8e, 0x0a, 0x6e, 0xce, 0x45, 0x1d, 0x58, 0xd7, 0x6e, 0xb2, 0xb3, 0xdb, 0xcb,
	0x5a, 0x5d, 0x25, 0x3f, 0x2a, 0xb8, 0x19, 0x13, 0xdd, 0x87, 0x32, 0xa7, 0x23, 0xa6, 0x7a, 0xc1,
	0xea, 0xdc, 0x58, 0xd6, 0xe8, 0xd3, 0x11, 0x3b, 0x2a, 0xb8, 0x8a, 0x85, 0x9e, 0x80, 0x39, 0xa4,
	0x0c, 0x87, 0xf4, 0x17, 0xa2, 0xba, 0xc2, 0xea, 0x34, 0x97, 0x35, 0x0e, 0x33, 0x86, 0x3c, 0x76,
	0xce, 0xee, 0xad, 0x41, 0x69, 0xcc, 0x47, 0xce, 0x36, 0x6c, 0x2d, 0x1d, 0xc1, 0x41, 0xd0, 0xb8,
	0xbc, 0x43, 0xa7, 0x01, 0x1b, 0x8b, 0x7b, 0x70, 0x76, 0x00, 0x2d, 0xfb, 0x70, 0x6e, 0xc0, 0x8e,
	0x4e, 0xe0, 0x62, 0x08, 0x9d, 0xbf, 0x8a, 0x50, 0xea, 0xd1, 0x00, 0xdd, 0x02, 0x48, 0xb0, 0x20,
	0xde, 0x90, 0x5e, 0x90, 0x20, 0xab, 0xd8, 0xaa, 0x44, 0x0e, 0x25, 0x20, 0x2b, 0x19, 0x8f, 0x75,
	0xbc, 0x4a, 0xae, 0xfc, 0x44, 0x6d, 0xd8, 0x1e, 0x53, 0x36, 0x6d, 0x7e, 0x6f, 0x10, 0x46, 0xfe,
	0x19, 0xcf, 0xee, 0x8a, 0xad, 0x31, 0x65, 0x79, 0xff, 0xf7, 0x94, 0x00, 0xdd, 0x06, 0x4b, 0x95,
	0x88, 0xc7, 0x22, 0xe6, 0x13, 0xbb, 0xa2, 0x6a, 0x18, 0x14, 0xf4, 0x42, 0x22, 0xb2, 0xc4, 0x35,
	0x41, 0x96, 0xb8, 0xa9, 0x4b, 0x5c, 0x01, 0x7d, 0x3a, 0x42, 0x0e, 0xd4, 0xc7, 0x69, 0x28, 0xa8,
	0x14, 0xaa, 0xf6, 0xae, 0x2a, 0x82, 0xa5, 0xc0, 0x3e, 0x1d, 0xc9, 0xe6, 0xbe, 0x09, 0x26, 0x8b,
	0x02, 0xe2, 0xc5, 0xe9, 0xc0, 0x06, 0x25, 0xae, 0xc8, 0xf5, 0xab, 0x74, 0x80, 0x1e, 0x42, 0x55,
	0x89, 0x70, 0x10, 0x24, 0xb6, 0xa5, 0x12, 0xb2, 0x9d, 0x27, 0xe4, 0x45, 0x14, 0x90, 0x6e, 0x10,
	0x24, 0x84, 0x73, 0x57, 0x19, 0x90, 0x0b, 0xd5, 0x70, 0xef, 0x30, 0xf3, 0xc4, 0x24, 0x26, 0x76,
	0x7d, 0xdf, 0x68, 0xd5, 0x5d, 0x53, 0x02, 0xaf, 0x27, 0x31, 0x41, 0x2d, 0x68, 0x0c, 0x53, 0x16,
	0x50, 0x36, 0xf2, 0x86, 0x84, 0x78, 0x32, 0x4c, 0xf6, 0x86, 0x3a, 0xf8, 0x46, 0x86, 0x1f, 0x12,
	0xe2, 0x62, 0x41, 0x4e, 0xca, 0x66, 0xb9, 0xb1, 0x76, 0x52, 0x36, 0xd7, 0x1a, 0xeb, 0x27, 0x65,
	0x73, 0xbd, 0x51, 0x39, 0x29, 0x9b, 0xb5, 0x46, 0x5d, 0x85, 0xbd, 0xcb, 0xcf, 0x3e, 0x2d, 0xec,
	0xf8, 0xe2, 0xa3, 0x61, 0xc7, 0x17, 0xff, 0x85, 0xfd, 0x8a, 0xb0, 0xb7, 0xc1, 0x3a, 0xc0, 0xcc,
	0x27, 0xa1, 0xbe, 0x81, 0x2e, 0x05, 0xc7, 0xb8, 0x1c, 0x1c, 0xe7, 0x0f, 0x03, 0x6a, 0xf3, 0x77,
	0xd8, 0xb5, 0x1a, 0xe8, 0x1b, 0xb0, 0x86, 0x98, 0x86, 0x5e, 0x42, 0x30, 0x8f, 0x98, 0xca, 0xdc,
	0x46, 0xe7, 0xf6, 0xaa, 0xfb, 0xb0, 0x7d, 0x88, 0x69, 0xe8, 0x2a, 0x9a, 0x0b, 0xc3, 0xe9, 0xb7,
	0x74, 0xa1, 0x2c, 0x70, 0x91, 0x50, 0x36, 0x52, 0x99, 0xad, 0x6a, 0x42, 0x5f, 0x21, 0xce, 0x2d,
	0x80, 0x99, 0x2a, 0xda, 0x04, 0xeb, 0xf8, 0xc5, 0x9b, 0xee, 0xf7, 0xc7, 0xcf, 0xbd, 0xee, 0xe9,
	0xeb, 0x46, 0xc1, 0x79, 0x03, 0x6b, 0xc7, 0x2c, 0x4e, 0xe5, 0x95, 0x65, 0xca, 0x67, 0xee, 0xca,
	0x01, 0x61, 0xca, 0x90, 0x6e, 0xa9, 0x54, 0xf3, 0x66, 0xef, 0x53, 0xc9, 0x05, 0x05, 0xa9, 0x17,
	0xdf, 0xf9, 0xbb, 0x98, 0xbf, 0x50, 0xa7, 0x51, 0x40, 0x87, 0x93, 0x7f, 0x67, 0x26, 0xb9, 0x0f,
	0xc0, 0xc8, 0xb9, 0xa7, 0xfc, 0xf0, 0xec, 0x3e, 0xae, 0xcf, 0xc2, 0x15, 0xa7, 0xc2, 0xad, 0x32,
	0x72, 0xae, 0xbe, 0x38, 0x3a, 0x86, 0x4a, 0xfe, 0x72, 0x97, 0xd4, 0xcb, 0xfd, 0x60, 0xf1, 0xe5,
	0x5e, 0xb5, 0xb3, 0xf6, 0xc2, 0xab, 0x9d, 0xeb, 0xcb, 0x46, 0x92, 0x8e, 0xf3, 0x3d, 0x0f, 0x70,
	0x28, 0x0b, 0x23, 0x9b, 0x61, 0xb6, 0x18, 0x39, 0xcf, 0xac, 0xf4, 0xb4, 0x00, 0x75, 0xc1, 0x9a,
	0xe3, 0xab, 0x09, 0xc6, 0xea, 0xec, 0x2f, 0xba, 0x5f, 0x1e, 0xd5, 0x5c, 0x98, 0x59, 0x6a, 0x3e,
	0x85, 0xda, 0x27, 0x8f, 0x07, 0xbf, 0x19, 0xb0, 0xbb, 0xf2, 0x8c, 0xd9, 0x4b, 0x7c, 0x0f, 0x36,
	0xe7, 0x8f, 0x33, 0x1b, 0x13, 0xea, 0xb3, 0x0d, 0xc8, 0x8e, 0xfe, 0x0a, 0xb6, 0xe6, 0x79, 0x3a,
	0x55, 0xc5, 0x8f, 0xa4, 0x6a, 0x73, 0xa6, 0xab, 0x00, 0xe7, 0x19, 0x58, 0x73, 0x7d, 0x8b, 0x6c,
	0xa8, 0x30, 0x22, 0xce, 0xa3, 0x44, 0x8f, 0x19, 0x55, 0x37, 0x5f, 0x22, 0x04, 0x65, 0xd5, 0xf4,
	0x45, 0x05, 0xab, 0x6f, 0xe7, 0x27, 0x30, 0x73, 0xcb, 0xe8, 0x33, 0x00, 0x71, 0x41, 0x03, 0x6f,
	0x30, 0x11, 0x84, 0xe7, 0x6d, 0x34, 0x43, 0x50, 0x13, 0x4c, 0xb5, 0xe2, 0x22, 0xb7, 0x31, 0x5d,
	0x23, 0x07, 0x6a, 0x3a, 0x89, 0x1e, 0x65, 0x01, 0xb9, 0x50, 0x1d, 0x52, 0x77, 0x17, 0xb0, 0xce,
	0xef, 0x65, 0xf8, 0xff, 0xc1, 0x3b, 0xcc, 0x18, 0x09, 0xb3, 0x07, 0x8f, 0x90, 0x44, 0xc7, 0x0f,
	0xb9, 0x60, 0xcd, 0x25, 0x0a, 0x5d, 0x9b, 0xc3, 0xe6, 0x9d, 0x2b, 0x18, 0x59, 0xf8, 0x7f, 0x80,
	0xda, 0xfc, 0xdc, 0x86, 0xee, 0x5c, 0x3b, 0x51, 0x36, 0x9d, 0xab, 0x28, 0x99, 0xd9, 0xb7, 0x50,
	0x5f, 0x48, 0x37, 0x72, 0xae, 0xaf, 0xf7, 0xe6, 0xdd, 0x2b, 0x39, 0x99, 0xe5, 0x43, 0xb0, 0xfa,
	0xe9, 0x60, 0x4c, 0x85, 0xbe, 0xd7, 0x9a, 0x8b, 0x3a, 0xf3, 0x83, 0x64, 0x73, 0x77, 0xa5, 0x6c,
	0x66, 0x67, 0xfe, 0x46, 0xfd, 0x64, 0x3b, 0x3f, 0xc2, 0xff, 0xfa, 0xe9, 0x40, 0xfe, 0x96, 0x0c,
	0x48, 0x4f, 0xcd, 0x37, 0x3a, 0x6d, 0x68, 0x2f, 0xd7, 0x5a, 0x35, 0x01, 0x36, 0xf7, 0x16, 0x6d,
	0x2e, 0x4a, 0x5b, 0xc6, 0x43, 0x63, 0xb0, 0xae, 0xfe, 0xa7, 0x1e, 0xfd, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x80, 0x2b, 0x37, 0xd9, 0x85, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChannelAuctioneerServerClient is the client API for ChannelAuctioneerServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChannelAuctioneerServerClient interface {
	InitAccount(ctx context.Context, in *ServerInitAccountRequest, opts ...grpc.CallOption) (*ServerInitAccountResponse, error)
	CloseAccount(ctx context.Context, in *ServerCloseAccountRequest, opts ...grpc.CallOption) (*ServerCloseAccountResponse, error)
	ModifyAccount(ctx context.Context, in *ServerModifyAccountRequest, opts ...grpc.CallOption) (*ServerModifyAccountResponse, error)
	SubmitOrder(ctx context.Context, in *ServerOrderRequest, opts ...grpc.CallOption) (*ServerOrderResponse, error)
	CancelOrder(ctx context.Context, in *ServerOrderRequest, opts ...grpc.CallOption) (*ServerOrderResponse, error)
	SubscribeBatchAuction(ctx context.Context, opts ...grpc.CallOption) (ChannelAuctioneerServer_SubscribeBatchAuctionClient, error)
}

type channelAuctioneerServerClient struct {
	cc *grpc.ClientConn
}

func NewChannelAuctioneerServerClient(cc *grpc.ClientConn) ChannelAuctioneerServerClient {
	return &channelAuctioneerServerClient{cc}
}

func (c *channelAuctioneerServerClient) InitAccount(ctx context.Context, in *ServerInitAccountRequest, opts ...grpc.CallOption) (*ServerInitAccountResponse, error) {
	out := new(ServerInitAccountResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.ChannelAuctioneerServer/InitAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAuctioneerServerClient) CloseAccount(ctx context.Context, in *ServerCloseAccountRequest, opts ...grpc.CallOption) (*ServerCloseAccountResponse, error) {
	out := new(ServerCloseAccountResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.ChannelAuctioneerServer/CloseAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAuctioneerServerClient) ModifyAccount(ctx context.Context, in *ServerModifyAccountRequest, opts ...grpc.CallOption) (*ServerModifyAccountResponse, error) {
	out := new(ServerModifyAccountResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.ChannelAuctioneerServer/ModifyAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAuctioneerServerClient) SubmitOrder(ctx context.Context, in *ServerOrderRequest, opts ...grpc.CallOption) (*ServerOrderResponse, error) {
	out := new(ServerOrderResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.ChannelAuctioneerServer/SubmitOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAuctioneerServerClient) CancelOrder(ctx context.Context, in *ServerOrderRequest, opts ...grpc.CallOption) (*ServerOrderResponse, error) {
	out := new(ServerOrderResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.ChannelAuctioneerServer/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAuctioneerServerClient) SubscribeBatchAuction(ctx context.Context, opts ...grpc.CallOption) (ChannelAuctioneerServer_SubscribeBatchAuctionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChannelAuctioneerServer_serviceDesc.Streams[0], "/clmrpc.ChannelAuctioneerServer/SubscribeBatchAuction", opts...)
	if err != nil {
		return nil, err
	}
	x := &channelAuctioneerServerSubscribeBatchAuctionClient{stream}
	return x, nil
}

type ChannelAuctioneerServer_SubscribeBatchAuctionClient interface {
	Send(*ClientAuctionMessage) error
	Recv() (*ServerAuctionMessage, error)
	grpc.ClientStream
}

type channelAuctioneerServerSubscribeBatchAuctionClient struct {
	grpc.ClientStream
}

func (x *channelAuctioneerServerSubscribeBatchAuctionClient) Send(m *ClientAuctionMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *channelAuctioneerServerSubscribeBatchAuctionClient) Recv() (*ServerAuctionMessage, error) {
	m := new(ServerAuctionMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChannelAuctioneerServerServer is the server API for ChannelAuctioneerServer service.
type ChannelAuctioneerServerServer interface {
	InitAccount(context.Context, *ServerInitAccountRequest) (*ServerInitAccountResponse, error)
	CloseAccount(context.Context, *ServerCloseAccountRequest) (*ServerCloseAccountResponse, error)
	ModifyAccount(context.Context, *ServerModifyAccountRequest) (*ServerModifyAccountResponse, error)
	SubmitOrder(context.Context, *ServerOrderRequest) (*ServerOrderResponse, error)
	CancelOrder(context.Context, *ServerOrderRequest) (*ServerOrderResponse, error)
	SubscribeBatchAuction(ChannelAuctioneerServer_SubscribeBatchAuctionServer) error
}

func RegisterChannelAuctioneerServerServer(s *grpc.Server, srv ChannelAuctioneerServerServer) {
	s.RegisterService(&_ChannelAuctioneerServer_serviceDesc, srv)
}

func _ChannelAuctioneerServer_InitAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInitAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAuctioneerServerServer).InitAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.ChannelAuctioneerServer/InitAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAuctioneerServerServer).InitAccount(ctx, req.(*ServerInitAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAuctioneerServer_CloseAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerCloseAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAuctioneerServerServer).CloseAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.ChannelAuctioneerServer/CloseAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAuctioneerServerServer).CloseAccount(ctx, req.(*ServerCloseAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAuctioneerServer_ModifyAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerModifyAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAuctioneerServerServer).ModifyAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.ChannelAuctioneerServer/ModifyAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAuctioneerServerServer).ModifyAccount(ctx, req.(*ServerModifyAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAuctioneerServer_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAuctioneerServerServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.ChannelAuctioneerServer/SubmitOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAuctioneerServerServer).SubmitOrder(ctx, req.(*ServerOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAuctioneerServer_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAuctioneerServerServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.ChannelAuctioneerServer/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAuctioneerServerServer).CancelOrder(ctx, req.(*ServerOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAuctioneerServer_SubscribeBatchAuction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChannelAuctioneerServerServer).SubscribeBatchAuction(&channelAuctioneerServerSubscribeBatchAuctionServer{stream})
}

type ChannelAuctioneerServer_SubscribeBatchAuctionServer interface {
	Send(*ServerAuctionMessage) error
	Recv() (*ClientAuctionMessage, error)
	grpc.ServerStream
}

type channelAuctioneerServerSubscribeBatchAuctionServer struct {
	grpc.ServerStream
}

func (x *channelAuctioneerServerSubscribeBatchAuctionServer) Send(m *ServerAuctionMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *channelAuctioneerServerSubscribeBatchAuctionServer) Recv() (*ClientAuctionMessage, error) {
	m := new(ClientAuctionMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChannelAuctioneerServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clmrpc.ChannelAuctioneerServer",
	HandlerType: (*ChannelAuctioneerServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitAccount",
			Handler:    _ChannelAuctioneerServer_InitAccount_Handler,
		},
		{
			MethodName: "CloseAccount",
			Handler:    _ChannelAuctioneerServer_CloseAccount_Handler,
		},
		{
			MethodName: "ModifyAccount",
			Handler:    _ChannelAuctioneerServer_ModifyAccount_Handler,
		},
		{
			MethodName: "SubmitOrder",
			Handler:    _ChannelAuctioneerServer_SubmitOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _ChannelAuctioneerServer_CancelOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeBatchAuction",
			Handler:       _ChannelAuctioneerServer_SubscribeBatchAuction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}
