// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package postgres

import ()

type Account struct {
	TraderKey           []byte
	TokenID             []byte
	Value               int64
	Expiry              int64
	AuctioneerKeyFamily int64
	AuctioneerKeyIndex  int64
	AuctioneerPublicKey []byte
	BatchKey            []byte
	Secret              []byte
	State               int16
	HeightHint          int64
	OutPointHash        []byte
	OutPointIndex       int64
	LatestTx            []byte
	UserAgent           string
}

type AccountBan struct {
	ID           int64
	Disabled     bool
	TraderKey    []byte
	ExpiryHeight int64
	Duration     int64
}

type AccountDiff struct {
	ID                  int64
	TraderKey           []byte
	Confirmed           bool
	TokenID             []byte
	Value               int64
	Expiry              int64
	AuctioneerKeyFamily int64
	AuctioneerKeyIndex  int64
	AuctioneerPublicKey []byte
	BatchKey            []byte
	Secret              []byte
	State               int16
	HeightHint          int64
	OutPointHash        []byte
	OutPointIndex       int64
	LatestTx            []byte
	UserAgent           string
}

type AccountReservation struct {
	TraderKey           []byte
	Value               int64
	AuctioneerKeyFamily int64
	AuctioneerKeyIndex  int64
	AuctioneerPublicKey []byte
	InitialBatchKey     []byte
	Expiry              int64
	HeightHint          int64
	TokenID             []byte
}

type AuctioneerAccount struct {
	Balance             int64
	BatchKey            []byte
	IsPending           bool
	AuctioneerKeyFamily int64
	AuctioneerKeyIndex  int64
	AuctioneerPublicKey []byte
	OutPointHash        []byte
	OutPointIndex       int64
}

type LeaseDuration struct {
	Duration int64
	State    int16
}

type LifetimePackage struct {
	ChannelPointString  string
	ChannelPointHash    []byte
	ChannelPointIndex   int64
	ChannelScript       []byte
	HeightHint          int64
	MaturityHeight      int64
	Version             int16
	AskAccountKey       []byte
	BidAccountKey       []byte
	AskNodeKey          []byte
	BidNodeKey          []byte
	AskPaymentBasePoint []byte
	BidPaymentBasePoint []byte
}

type NodeBan struct {
	ID           int64
	Disabled     bool
	NodeKey      []byte
	ExpiryHeight int64
	Duration     int64
}
