ALTER TABLE account_reservations ADD version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD version SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE account_diffs ADD version SMALLINT NOT NULL DEFAULT 0;
