// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package adminrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lightninglabs/llm/clmrpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type MasterAccountResponse struct {
	//*
	//OutPoint is the outpoint of the master account. If this is a zero outpoint,
	//then no account exists yet.
	Outpoint *OutPoint `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	//*
	//Balance is the current balance of the master account.
	Balance int64 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	//*
	//AuctioneerKey is the base key for the auctioneer, this is a static parameter
	//that's created when the system is initialized.
	KeyDescriptor *KeyDescriptor `protobuf:"bytes,3,opt,name=key_descriptor,json=keyDescriptor,proto3" json:"key_descriptor,omitempty"`
	//*
	//BatchKey is the current batch key for the auctioneer's account, this will be
	//incremented by one each batch.
	BatchKey             []byte   `protobuf:"bytes,4,opt,name=batch_key,json=batchKey,proto3" json:"batch_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterAccountResponse) Reset()         { *m = MasterAccountResponse{} }
func (m *MasterAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MasterAccountResponse) ProtoMessage()    {}
func (*MasterAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{2}
}

func (m *MasterAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterAccountResponse.Unmarshal(m, b)
}
func (m *MasterAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterAccountResponse.Marshal(b, m, deterministic)
}
func (m *MasterAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterAccountResponse.Merge(m, src)
}
func (m *MasterAccountResponse) XXX_Size() int {
	return xxx_messageInfo_MasterAccountResponse.Size(m)
}
func (m *MasterAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterAccountResponse proto.InternalMessageInfo

func (m *MasterAccountResponse) GetOutpoint() *OutPoint {
	if m != nil {
		return m.Outpoint
	}
	return nil
}

func (m *MasterAccountResponse) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *MasterAccountResponse) GetKeyDescriptor() *KeyDescriptor {
	if m != nil {
		return m.KeyDescriptor
	}
	return nil
}

func (m *MasterAccountResponse) GetBatchKey() []byte {
	if m != nil {
		return m.BatchKey
	}
	return nil
}

type ConnectedTradersResponse struct {
	//*
	//A map of all connected trader streams. The key is the hex-encoded LSAT ID
	//of a connected stream and the content is a list of all account keys that
	//trader connection has sent subscriptions for.
	Streams              map[string]*PubKeyList `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ConnectedTradersResponse) Reset()         { *m = ConnectedTradersResponse{} }
func (m *ConnectedTradersResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectedTradersResponse) ProtoMessage()    {}
func (*ConnectedTradersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{3}
}

func (m *ConnectedTradersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectedTradersResponse.Unmarshal(m, b)
}
func (m *ConnectedTradersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectedTradersResponse.Marshal(b, m, deterministic)
}
func (m *ConnectedTradersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectedTradersResponse.Merge(m, src)
}
func (m *ConnectedTradersResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectedTradersResponse.Size(m)
}
func (m *ConnectedTradersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectedTradersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectedTradersResponse proto.InternalMessageInfo

func (m *ConnectedTradersResponse) GetStreams() map[string]*PubKeyList {
	if m != nil {
		return m.Streams
	}
	return nil
}

type PubKeyList struct {
	//*
	//The raw bytes of the key being identified.
	RawKeyBytes          [][]byte `protobuf:"bytes,1,rep,name=raw_key_bytes,json=rawKeyBytes,proto3" json:"raw_key_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubKeyList) Reset()         { *m = PubKeyList{} }
func (m *PubKeyList) String() string { return proto.CompactTextString(m) }
func (*PubKeyList) ProtoMessage()    {}
func (*PubKeyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{4}
}

func (m *PubKeyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubKeyList.Unmarshal(m, b)
}
func (m *PubKeyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubKeyList.Marshal(b, m, deterministic)
}
func (m *PubKeyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubKeyList.Merge(m, src)
}
func (m *PubKeyList) XXX_Size() int {
	return xxx_messageInfo_PubKeyList.Size(m)
}
func (m *PubKeyList) XXX_DiscardUnknown() {
	xxx_messageInfo_PubKeyList.DiscardUnknown(m)
}

var xxx_messageInfo_PubKeyList proto.InternalMessageInfo

func (m *PubKeyList) GetRawKeyBytes() [][]byte {
	if m != nil {
		return m.RawKeyBytes
	}
	return nil
}

type OutPoint struct {
	//*
	//Raw bytes representing the transaction id.
	Txid []byte `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	//*
	//The index of the output on the transaction.
	OutputIndex          uint32   `protobuf:"varint,2,opt,name=output_index,proto3" json:"output_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutPoint) Reset()         { *m = OutPoint{} }
func (m *OutPoint) String() string { return proto.CompactTextString(m) }
func (*OutPoint) ProtoMessage()    {}
func (*OutPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{5}
}

func (m *OutPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutPoint.Unmarshal(m, b)
}
func (m *OutPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutPoint.Marshal(b, m, deterministic)
}
func (m *OutPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutPoint.Merge(m, src)
}
func (m *OutPoint) XXX_Size() int {
	return xxx_messageInfo_OutPoint.Size(m)
}
func (m *OutPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_OutPoint.DiscardUnknown(m)
}

var xxx_messageInfo_OutPoint proto.InternalMessageInfo

func (m *OutPoint) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *OutPoint) GetOutputIndex() uint32 {
	if m != nil {
		return m.OutputIndex
	}
	return 0
}

type KeyLocator struct {
	/// The family of key being identified.
	KeyFamily int32 `protobuf:"varint,1,opt,name=key_family,json=keyFamily,proto3" json:"key_family,omitempty"`
	/// The precise index of the key being identified.
	KeyIndex             int32    `protobuf:"varint,2,opt,name=key_index,json=keyIndex,proto3" json:"key_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyLocator) Reset()         { *m = KeyLocator{} }
func (m *KeyLocator) String() string { return proto.CompactTextString(m) }
func (*KeyLocator) ProtoMessage()    {}
func (*KeyLocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{6}
}

func (m *KeyLocator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyLocator.Unmarshal(m, b)
}
func (m *KeyLocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyLocator.Marshal(b, m, deterministic)
}
func (m *KeyLocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyLocator.Merge(m, src)
}
func (m *KeyLocator) XXX_Size() int {
	return xxx_messageInfo_KeyLocator.Size(m)
}
func (m *KeyLocator) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyLocator.DiscardUnknown(m)
}

var xxx_messageInfo_KeyLocator proto.InternalMessageInfo

func (m *KeyLocator) GetKeyFamily() int32 {
	if m != nil {
		return m.KeyFamily
	}
	return 0
}

func (m *KeyLocator) GetKeyIndex() int32 {
	if m != nil {
		return m.KeyIndex
	}
	return 0
}

type KeyDescriptor struct {
	//*
	//The raw bytes of the key being identified.
	RawKeyBytes []byte `protobuf:"bytes,1,opt,name=raw_key_bytes,json=rawKeyBytes,proto3" json:"raw_key_bytes,omitempty"`
	//*
	//The key locator that identifies which key to use for signing.
	KeyLoc               *KeyLocator `protobuf:"bytes,2,opt,name=key_loc,json=keyLoc,proto3" json:"key_loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *KeyDescriptor) Reset()         { *m = KeyDescriptor{} }
func (m *KeyDescriptor) String() string { return proto.CompactTextString(m) }
func (*KeyDescriptor) ProtoMessage()    {}
func (*KeyDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{7}
}

func (m *KeyDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyDescriptor.Unmarshal(m, b)
}
func (m *KeyDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyDescriptor.Marshal(b, m, deterministic)
}
func (m *KeyDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDescriptor.Merge(m, src)
}
func (m *KeyDescriptor) XXX_Size() int {
	return xxx_messageInfo_KeyDescriptor.Size(m)
}
func (m *KeyDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDescriptor proto.InternalMessageInfo

func (m *KeyDescriptor) GetRawKeyBytes() []byte {
	if m != nil {
		return m.RawKeyBytes
	}
	return nil
}

func (m *KeyDescriptor) GetKeyLoc() *KeyLocator {
	if m != nil {
		return m.KeyLoc
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "adminrpc.EmptyRequest")
	proto.RegisterType((*EmptyResponse)(nil), "adminrpc.EmptyResponse")
	proto.RegisterType((*MasterAccountResponse)(nil), "adminrpc.MasterAccountResponse")
	proto.RegisterType((*ConnectedTradersResponse)(nil), "adminrpc.ConnectedTradersResponse")
	proto.RegisterMapType((map[string]*PubKeyList)(nil), "adminrpc.ConnectedTradersResponse.StreamsEntry")
	proto.RegisterType((*PubKeyList)(nil), "adminrpc.PubKeyList")
	proto.RegisterType((*OutPoint)(nil), "adminrpc.OutPoint")
	proto.RegisterType((*KeyLocator)(nil), "adminrpc.KeyLocator")
	proto.RegisterType((*KeyDescriptor)(nil), "adminrpc.KeyDescriptor")
}

func init() { proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c) }

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9b, 0xa6, 0x49, 0x26, 0x76, 0xa9, 0x56, 0x40, 0xac, 0x20, 0x44, 0xe4, 0x53, 0x84,
	0x44, 0x8a, 0xc2, 0x05, 0x21, 0x84, 0x94, 0x40, 0x51, 0xab, 0xf0, 0x11, 0x2d, 0xbd, 0x47, 0xeb,
	0xf5, 0x20, 0x2c, 0x27, 0xbb, 0x66, 0xbd, 0xa6, 0xdd, 0x5f, 0xc6, 0x8d, 0x9f, 0xc3, 0xef, 0x40,
	0xbb, 0x26, 0x71, 0xd2, 0x36, 0xea, 0x6d, 0x67, 0xde, 0xcc, 0x9b, 0x79, 0xe3, 0x67, 0xe8, 0xb2,
	0x64, 0x95, 0x8a, 0x51, 0xae, 0xa4, 0x96, 0xa4, 0xed, 0x02, 0x95, 0xf3, 0x7e, 0x8f, 0x2f, 0x57,
	0x2a, 0xe7, 0xa7, 0xac, 0xe4, 0x3a, 0x95, 0x02, 0x51, 0x55, 0x25, 0xd1, 0x31, 0xf8, 0x67, 0xab,
	0x5c, 0x1b, 0x8a, 0x3f, 0x4b, 0x2c, 0x74, 0xf4, 0x00, 0x82, 0xff, 0x71, 0x91, 0x4b, 0x51, 0x60,
	0xf4, 0xc7, 0x83, 0x47, 0x9f, 0x59, 0xa1, 0x51, 0x4d, 0x38, 0x97, 0xa5, 0xd0, 0x6b, 0x84, 0x8c,
	0xa0, 0x2d, 0x4b, 0x9d, 0xcb, 0x54, 0xe8, 0xd0, 0x1b, 0x78, 0xc3, 0xee, 0x98, 0x8c, 0xd6, 0x03,
	0x47, 0x5f, 0x4b, 0x3d, 0xb7, 0x08, 0xdd, 0xd4, 0x90, 0x10, 0x5a, 0x31, 0x5b, 0x32, 0xc1, 0x31,
	0x3c, 0x18, 0x78, 0xc3, 0x06, 0x5d, 0x87, 0xe4, 0x1d, 0x1c, 0x67, 0x68, 0x16, 0x09, 0x16, 0x5c,
	0xa5, 0xb9, 0x96, 0x2a, 0x6c, 0x38, 0xbe, 0x5e, 0xcd, 0x37, 0x43, 0xf3, 0x61, 0x03, 0xd3, 0x20,
	0xdb, 0x0e, 0xc9, 0x13, 0xe8, 0xc4, 0x4c, 0xf3, 0x1f, 0x8b, 0x0c, 0x4d, 0x78, 0x38, 0xf0, 0x86,
	0x3e, 0x6d, 0xbb, 0xc4, 0x0c, 0x4d, 0xf4, 0xdb, 0x83, 0xf0, 0xbd, 0x14, 0x02, 0xb9, 0xc6, 0xe4,
	0x52, 0xb1, 0x04, 0x55, 0xb1, 0xd1, 0x70, 0x01, 0xad, 0x42, 0x2b, 0x64, 0xab, 0x22, 0xf4, 0x06,
	0x8d, 0x61, 0x77, 0x7c, 0x5a, 0x8f, 0xdc, 0xd7, 0x34, 0xfa, 0x56, 0x75, 0x9c, 0x09, 0xad, 0x0c,
	0x5d, 0xf7, 0xf7, 0xe7, 0xe0, 0x6f, 0x03, 0xe4, 0x04, 0x1a, 0x76, 0x1d, 0x7b, 0x99, 0x0e, 0xb5,
	0x4f, 0xf2, 0x1c, 0x9a, 0xbf, 0xd8, 0xb2, 0xac, 0xe4, 0x77, 0xc7, 0x0f, 0xeb, 0x51, 0xf3, 0x32,
	0x9e, 0xa1, 0xf9, 0x94, 0x16, 0x9a, 0x56, 0x25, 0x6f, 0x0e, 0x5e, 0x7b, 0xd1, 0x4b, 0x80, 0x1a,
	0x20, 0x11, 0x04, 0x8a, 0x5d, 0x59, 0x89, 0x8b, 0xd8, 0x68, 0xac, 0x16, 0xf6, 0x69, 0x57, 0xb1,
	0xab, 0x19, 0x9a, 0xa9, 0x4d, 0x45, 0x53, 0x68, 0xaf, 0x0f, 0x4f, 0x08, 0x1c, 0xea, 0xeb, 0x34,
	0x71, 0x0b, 0xf8, 0xd4, 0xbd, 0x49, 0x04, 0xbe, 0xfd, 0x1c, 0xa5, 0x5e, 0xa4, 0x22, 0xc1, 0x6b,
	0xb7, 0x48, 0x40, 0x77, 0x72, 0xd1, 0x39, 0x80, 0x1d, 0x29, 0x39, 0xb3, 0xa7, 0x7d, 0x0a, 0x60,
	0x27, 0x7e, 0x67, 0xab, 0x74, 0x59, 0x89, 0x69, 0xd2, 0x4e, 0x86, 0xe6, 0xa3, 0x4b, 0xd8, 0xcb,
	0x5b, 0xb8, 0x66, 0x6b, 0xd2, 0x76, 0x86, 0xe6, 0xc2, 0x31, 0xc5, 0x10, 0xec, 0x7c, 0xb6, 0xbb,
	0x24, 0x78, 0x37, 0x24, 0x90, 0x17, 0xd0, 0xb2, 0xf8, 0x52, 0xf2, 0xdb, 0x67, 0xaa, 0xf7, 0xa2,
	0x47, 0x99, 0x7b, 0x8f, 0xff, 0x7a, 0xe0, 0x4f, 0x2a, 0x53, 0x4f, 0x6c, 0x19, 0x39, 0x87, 0x60,
	0xc7, 0xae, 0xe4, 0x71, 0xdd, 0xbf, 0xed, 0xf4, 0xfe, 0xb3, 0x3a, 0x7f, 0xb7, 0xbf, 0xbf, 0xc0,
	0xc9, 0x4d, 0x0b, 0xec, 0x25, 0x8b, 0xee, 0xb7, 0x0d, 0x79, 0x0b, 0x9d, 0xa9, 0x35, 0xe5, 0x65,
	0xca, 0xb3, 0xbd, 0x44, 0xbd, 0x5b, 0xf9, 0xaa, 0x3b, 0x3e, 0x72, 0xff, 0xeb, 0xab, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0xe8, 0xff, 0xde, 0xe1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuctionAdminClient is the client API for AuctionAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuctionAdminClient interface {
	MasterAccount(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*MasterAccountResponse, error)
	ConnectedTraders(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ConnectedTradersResponse, error)
	BatchTick(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type auctionAdminClient struct {
	cc *grpc.ClientConn
}

func NewAuctionAdminClient(cc *grpc.ClientConn) AuctionAdminClient {
	return &auctionAdminClient{cc}
}

func (c *auctionAdminClient) MasterAccount(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*MasterAccountResponse, error) {
	out := new(MasterAccountResponse)
	err := c.cc.Invoke(ctx, "/adminrpc.AuctionAdmin/MasterAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionAdminClient) ConnectedTraders(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ConnectedTradersResponse, error) {
	out := new(ConnectedTradersResponse)
	err := c.cc.Invoke(ctx, "/adminrpc.AuctionAdmin/ConnectedTraders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionAdminClient) BatchTick(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/adminrpc.AuctionAdmin/BatchTick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionAdminServer is the server API for AuctionAdmin service.
type AuctionAdminServer interface {
	MasterAccount(context.Context, *EmptyRequest) (*MasterAccountResponse, error)
	ConnectedTraders(context.Context, *EmptyRequest) (*ConnectedTradersResponse, error)
	BatchTick(context.Context, *EmptyRequest) (*EmptyResponse, error)
}

// UnimplementedAuctionAdminServer can be embedded to have forward compatible implementations.
type UnimplementedAuctionAdminServer struct {
}

func (*UnimplementedAuctionAdminServer) MasterAccount(ctx context.Context, req *EmptyRequest) (*MasterAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MasterAccount not implemented")
}
func (*UnimplementedAuctionAdminServer) ConnectedTraders(ctx context.Context, req *EmptyRequest) (*ConnectedTradersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectedTraders not implemented")
}
func (*UnimplementedAuctionAdminServer) BatchTick(ctx context.Context, req *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchTick not implemented")
}

func RegisterAuctionAdminServer(s *grpc.Server, srv AuctionAdminServer) {
	s.RegisterService(&_AuctionAdmin_serviceDesc, srv)
}

func _AuctionAdmin_MasterAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionAdminServer).MasterAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminrpc.AuctionAdmin/MasterAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionAdminServer).MasterAccount(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionAdmin_ConnectedTraders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionAdminServer).ConnectedTraders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminrpc.AuctionAdmin/ConnectedTraders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionAdminServer).ConnectedTraders(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionAdmin_BatchTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionAdminServer).BatchTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminrpc.AuctionAdmin/BatchTick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionAdminServer).BatchTick(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuctionAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adminrpc.AuctionAdmin",
	HandlerType: (*AuctionAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MasterAccount",
			Handler:    _AuctionAdmin_MasterAccount_Handler,
		},
		{
			MethodName: "ConnectedTraders",
			Handler:    _AuctionAdmin_ConnectedTraders_Handler,
		},
		{
			MethodName: "BatchTick",
			Handler:    _AuctionAdmin_BatchTick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
