name: Docker image build

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

env:
  DOCKER_REPO: 923662548032.dkr.ecr.us-west-2.amazonaws.com/lightninglabs
  DOCKER_IMAGE: subasta

jobs:
  docker-build-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}:${{ env.RELEASE_VERSION }}"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Build and push
        id: docker_build_regtest
        uses: docker/build-push-action@v2
        with:
          file: regtest.Dockerfile
          push: true
          tags: "${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}:${{ env.RELEASE_VERSION }}-regtest-only"

      - name: Image digest regtest
        run: echo ${{ steps.docker_build_regtest.outputs.digest }}
