name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    shell: bash

env:
  # go needs absolute directories, using the $HOME variable doesn't work here.
  GOCACHE: /home/runner/work/go/pkg/build
  GOPATH: /home/runner/work/go
  GO111MODULE: on

  # If you change this value, please change it in the following files as well:
  # /Dockerfile
  # /regtest.Dockerfile
  GO_VERSION: 1.17.2

jobs:
  ########################
  # RPC compilation check
  ########################
  rpc-check:
    name: RPC compilation check
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: docker image cache
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: run check
        run: make rpc-check
      
      - name: compile regtest binary
        run: make regtest-build


  ############################
  # Mock generation and check 
  ############################
  mockgen-check:
    name: Mockgen check
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: docker image cache
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Generate mocks
        run: make mock

      - name: run check
        run: make mock-check

  ########################
  # lint code
  ########################
  lint:
    name: lint code
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Fetch all history for linter
        run: git fetch --prune --unshallow

      - name: go cache
        uses: actions/cache@v1
        with:
          path: /home/runner/work/go
          key: subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
            subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-
            subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-
            subasta-${{ runner.os }}-go-

      - name: setup go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: '~${{ env.GO_VERSION }}'

      - name: lint
        run: make lint

  ########################
  # run unit tests
  ########################
  unit-test:
    name: run unit tests
    runs-on: ubuntu-latest
    strategy:
      # Allow other tests in the matrix to continue if one fails.
      fail-fast: false
      matrix:
        unit_type:
          - unit-race
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: go cache
        uses: actions/cache@v1
        with:
          path: /home/runner/work/go
          key: subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
            subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-
            subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-
            subasta-${{ runner.os }}-go-

      - name: setup go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: '~${{ env.GO_VERSION }}'

      - name: run ${{ matrix.unit_type }}
        run: make ${{ matrix.unit_type }}

  ########################
  # run integration tests
  ########################
  integration-test:
    name: run itests
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: go cache
        uses: actions/cache@v1
        with:
          path: /home/runner/work/go
          key: subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
            subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-
            subasta-${{ runner.os }}-go-${{ env.GO_VERSION }}-
            subasta-${{ runner.os }}-go-

      - name: setup go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: '~${{ env.GO_VERSION }}'

      - name: run itest
        run: make itest

      - name: Zip log files on failure
        if: ${{ failure() }}
        run: 7z a logs-itest.zip itest/**/*.log

      - name: Upload log files on failure
        uses: actions/upload-artifact@v2.2.4
        if: ${{ failure() }}
        with:
          name: logs-itest
          path: logs-itest.zip
          retention-days: 5
